### ISSUE TITLE
Update for patch 6.1 API 6

### ISSUE THREAD

**Issue by ghost** [horoscope-dev/Dalamud.Divination.InstanceIDViewer#1]
hi, since the patch 6.1 it doesn't work anymore.

**Comment by SlashNephy** [comment]
Hi, I just updated 😁

**Comment by SlashNephy** [comment]
[v6.11.0](https://github.com/horoscope-dev/Dalamud.Divination.InstanceIDViewer/releases/tag/v6.11.0) was released to stable repository.
Please let me know if you have any problems!
